# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'testTagListView' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for testTagListView
  pod 'SnapKit', '3.2.0'

  target 'testTagListViewTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'testTagListViewUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
